### PR TITLE
Moved and renamed logos for consistency

### PR DESCRIPTION
**Pull request by zednotdead**
List of the logos is in README.md

### CODE REVIEW

**Comment by dxf** [comment]
Would prefer if it wasn't organized per folder, because I'm working on a gallery for the images and that would mess it up

**Comment by zednotdead** [comment]
Would renaming them like `Type_Name_LogoDetails.extension` be enough?

**Comment by TaranVH** [comment]
guys guys.
Keep in mind that these are my own files. I only put them on github 'caus eI couldn't think of a better place. I can't have people renaming and moving them, however good your intentions are. This is because of all the premiere projects that link back to them. You move or change a filename, now Premiere has no idea where it went. And if someone else moved it, now neither do I. 
I might actually have to mark this whole repo as "no contributions accepted."
Here's a taste of what can happen when you move and rename files. Now image that this list is 200 items long. I've been there before. It's not pretty. 
image

**Comment by dxf** [comment]
got it, @TaranVH 

I wouldn't have changed file names anyway, I just wanted to make a gallery for them haha

**Comment by zednotdead** [comment]
Gotcha. I'll close the pull request then.

**Pull request closed without merging**
