### PR TITLE
Fix some formatting in the README

### PR DESCRIPTION
**Pull request by willtheorangeguy**
The dots in front of file extensions made some of the sentences in your `README.md` hard to read, so I made them into inline `code` blocks so it's easier to read. 

Your repo has been very useful, and I thought that this was a good way to give back. +1 for creating this repo, it's a great collection.

Please let me know if there is something I can fix in this PR.

### CODE REVIEW

**Review by TaranVH — APPROVED** [review]

**Comment by willtheorangeguy** [comment]
Just wondering if you are going to merge this or not

**Comment by TaranVH** [comment]
oh i thought i had

**Comment by TaranVH** [comment]
ok, and I pulled origin on my github desktop. hopefully this does not cause merge conflicts as it did on the other repo when someone made changes to the readme and i had many hair pulling moments as github tried to overwrite a shitton of my locally changed files...

**Comment by willtheorangeguy** [comment]
OK good!

**Pull request merged**
